import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/tokens.css";
import "./styles/globals.css";
import { StoreProvider } from "./store/StoreProvider";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";
import { ScrollToTop } from "@/shared/ui/scroll-to-top";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
        <ScrollToTop />
      </body>
    </html>
  );
}
